ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER USUARIO_CAS IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO USUARIO_CAS;
ALTER USER USUARIO_CAS QUOTA UNLIMITED ON USERS;

CREATE USER USUARIO_LEG IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO USUARIO_LEG;
ALTER USER USUARIO_LEG QUOTA UNLIMITED ON USERS;