ALTER SESSION SET CONTAINER = XEPDB1;

-- CASILLEROS
CREATE USER USUARIO_CAS IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO USUARIO_CAS;
ALTER USER USUARIO_CAS QUOTA UNLIMITED ON USERS;

-- LEGAJOS
CREATE USER USUARIO_LEG IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO USUARIO_LEG;
ALTER USER USUARIO_LEG QUOTA UNLIMITED ON USERS;

-- USUARIOS (FALTANTE)
CREATE USER APP_ADMIN IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO APP_ADMIN;
ALTER USER APP_ADMIN QUOTA UNLIMITED ON USERS;